package com.ncs.nucleusproject1.app.security;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api")
public class CsrfController {

    @GetMapping("/set-xsrf-cookie")
    public void getCsrfToken() {
        // CSRF token is automatically generated by Spring Security and added as a cookie
    }
}


