#Source obtained from:
#https://help.aikido.dev/doc/github-action-setup-for-local-scanner/docn4KpccwdF
#workflow for code scanning only

name: Aikido Security
​on:
  push:
    branches:
      - main

name: Aikido Scan
jobs:
  aikido-local-scan-repo:
    runs-on: ubuntu-latest
    container:
      image: aikidosecurity/local-scanner:v1.0.52
    steps: 
      - uses: actions/checkout@v4 
        with: 
          token: ${{ secrets.GITHUB_TOKEN }} 
          path: ./backend/pom.xml
      - name: Run scan
        run: aikido-local-scanner scan my-repo --apikey ${{ secrets.AIKIDO_API_KEY }} --repositoryname gc-sus-backend --branchname main


      #format: sarif               # Specify output format as SARIF
      #output: aikido-results.sarif # Name of the SARIF results file

      #- name: Upload SARIF results
      #  if: always()
      #  uses: github/codeql-action/upload-sarif@v3
      #  with:
      #    sarif_file: aikido-results.sarif

      #- name: Run Snyk to check for vulnerabilities
      #  uses: snyk/actions/maven-3-jdk-17@master
      #  continue-on-error: true # To make sure that SARIF upload gets called
      #  env:
      #    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #  with:
      #    args: --sarif-file-output=snyk.sarif --file=./backend_nus/pom.xml
      #- name: Create SARIF directory and move SARIF files
      #  run: |
      #    mkdir sarif_files &&
      #    mv snyk.sarif sarif_files/
      #- name: Upload result to GitHub Code Scanning
      #  uses: github/codeql-action/upload-sarif@v3
      #  with:
      #    sarif_file: sarif_files
