#Source obtained from:
#https://github.com/snyk/actions/tree/master/maven-3-jdk-17
#workflow for code scanning only

name: Code scanning for maven via bearer
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  rule_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bearer
        id: report
        uses: bearer/bearer-action@2
        with:
          diff: true
          format: sarif
          output: results.sarif
      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
      #- name: Run Snyk to check for vulnerabilities
      #  uses: snyk/actions/maven-3-jdk-17@master
      #  continue-on-error: true # To make sure that SARIF upload gets called
      #  env:
      #    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #  with:
      #    args: --sarif-file-output=snyk.sarif --file=./backend_nus/pom.xml
      #- name: Create SARIF directory and move SARIF files
      #  run: |
      #    mkdir sarif_files &&
      #    mv snyk.sarif sarif_files/
      #- name: Upload result to GitHub Code Scanning
      #  uses: github/codeql-action/upload-sarif@v3
      #  with:
      #    sarif_file: sarif_files
